import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, CalendarDays, Check, ChefHat, ChevronRight, Clock3, CreditCard, Leaf, MapPin, Minus, Plus, Search, ShoppingBag, Sparkles, Store, Table2, Users, Utensils, X } from 'lucide-react';
import './index.css';

const img = 'assets/photo-1.jpg';
const menu = [
  { id: 1, name: 'Green goddess bowl', desc: 'Avocat, quinoa, légumes croquants, herbes fraîches', price: 14.9, cat: 'Bowls', image: img, tag: 'Best-seller' },
  { id: 2, name: 'Citrus salmon', desc: 'Saumon grillé, agrumes, riz sauvage & sauce verte', price: 18.5, cat: 'Plats', image: img },
  { id: 3, name: 'Mushroom toast', desc: 'Pain au levain, champignons, œuf coulant & roquette', price: 11.5, cat: 'Brunch', image: img },
  { id: 4, name: 'Tasty garden salad', desc: 'Tomates anciennes, burrata, pesto et graines torréfiées', price: 12.9, cat: 'Salades', image: img },
  { id: 5, name: 'Coconut chia cup', desc: 'Chia, coco, fruits de saison et granola maison', price: 7.5, cat: 'Desserts', image: img },
  { id: 6, name: 'Ginger lemonade', desc: 'Citron pressé, gingembre frais, menthe et eau pétillante', price: 5.5, cat: 'Boissons', image: img }
];
const cats = ['Tout', 'Bowls', 'Plats', 'Brunch', 'Salades', 'Desserts', 'Boissons'];

function Button({ children, className = '', onClick, variant = 'primary', type = 'button' }) {
  const style = variant === 'primary' ? 'bg-emerald text-white hover:bg-[#066c40]' : 'border border-emerald/20 text-emerald hover:bg-mint';
  return <button type={type} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition ${style} ${className}`}>{children}</button>;
}
function FoodCard({ item, add }) {
  return <article className="group overflow-hidden rounded-3xl border border-emerald/10 bg-white shadow-soft transition hover:-translate-y-1">
    <div className="relative h-44 overflow-hidden bg-mint"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-[11px] font-bold text-emerald">{item.tag || item.cat}</span></div>
    <div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-bold text-ink">{item.name}</h3><span className="whitespace-nowrap font-bold text-emerald">€{item.price.toFixed(2)}</span></div><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{item.desc}</p><button onClick={() => add(item)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-mint py-2.5 text-sm font-bold text-emerald transition hover:bg-lime"><Plus size={16}/> Ajouter</button></div>
  </article>;
}
function App() {
  const [category, setCategory] = useState('Tout');
  const [cart, setCart] = useState([]);
  const [view, setView] = useState('order');
  const [opsTab, setOpsTab] = useState('reservations');
  const [notice, setNotice] = useState('');
  const filtered = useMemo(() => category === 'Tout' ? menu : menu.filter(x => x.cat === category), [category]);
  const totalItems = cart.reduce((n, x) => n + x.qty, 0);
  const total = cart.reduce((n, x) => n + x.price * x.qty, 0);
  const add = item => setCart(c => c.some(x => x.id === item.id) ? c.map(x => x.id === item.id ? {...x, qty: x.qty + 1} : x) : [...c, {...item, qty: 1}]);
  const change = (id, amount) => setCart(c => c.map(x => x.id === id ? {...x, qty: x.qty + amount} : x).filter(x => x.qty > 0));
  const message = text => { setNotice(text); setTimeout(() => setNotice(''), 2800); };
  return <div className="min-h-screen bg-[#f7fbf9]">
    {notice && <div className="fixed left-1/2 top-5 z-50 flex -translate-x-1/2 items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white shadow-xl"><Check size={17} className="text-lime"/>{notice}</div>}
    <header className="sticky top-0 z-40 border-b border-emerald/10 bg-[#f7fbf9]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><a href="#top" className="flex items-center gap-2 text-xl font-black tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald text-white"><Leaf size={18}/></span>Tasty<span className="text-emerald">.</span></a><nav className="hidden items-center gap-8 text-sm font-medium text-slate-500 md:flex"><a href="#menu" className="hover:text-emerald">Menu</a><a href="#about" className="hover:text-emerald">Notre histoire</a><a href="#reserve" className="hover:text-emerald">Réserver</a><button onClick={() => setView('dashboard')} className="hover:text-emerald">Gestion restaurant</button></nav><div className="flex items-center gap-3"><button onClick={() => setView('dashboard')} className="hidden rounded-full p-2 text-slate-500 hover:bg-mint md:block" title="Gestion"><Store size={19}/></button><button onClick={() => setView('cart')} className="relative rounded-full bg-white p-3 text-emerald shadow-sm"><ShoppingBag size={19}/>{totalItems > 0 && <span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-emerald text-[10px] font-bold text-white">{totalItems}</span>}</button></div></div></header>
    {view === 'dashboard' ? <Dashboard setView={setView} tab={opsTab} setTab={setOpsTab} message={message}/> : view === 'cart' ? <Cart cart={cart} total={total} change={change} setView={setView} message={message}/> : <>
      <main id="top"><section className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-20 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:pt-20"><div className="fade-in"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-lime/60 px-4 py-2 text-xs font-bold text-emerald"><Sparkles size={14}/> 100% frais, 100% fait maison</div><h1 className="max-w-xl text-5xl font-black leading-[1.03] tracking-[-.05em] text-ink sm:text-7xl">Le bon goût,<br/><span className="text-emerald">sans détour.</span></h1><p className="mt-6 max-w-md text-lg leading-8 text-slate-500">Des plats colorés, généreux et préparés chaque jour avec les meilleurs ingrédients de saison.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#menu"><Button>Commander maintenant <ArrowRight size={17}/></Button></a><a href="#reserve"><Button variant="outline">Réserver une table</Button></a></div><div className="mt-9 flex items-center gap-3 text-sm text-slate-500"><div className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-orange-200">😊</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-blue-200">🙂</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-yellow-200">😋</span></div><span><b className="text-ink">4.9/5</b> par plus de 2 000 foodies</span></div></div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 rounded-[4rem] bg-lime/50 blur-2xl"/><img src={img} alt="Plat frais Tasty" className="relative aspect-square w-full rounded-[3rem] object-cover shadow-2xl"/><div className="absolute -bottom-5 -left-3 rounded-2xl bg-white p-4 shadow-soft sm:-left-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-mint text-emerald"><ChefHat/></span><div><p className="text-xs text-slate-400">Préparé avec soin</p><p className="font-bold">Cuisine du jour</p></div></div></div></div></section>
      <section id="menu" className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-emerald">À la carte</p><h2 className="text-4xl font-black tracking-tight text-ink">Notre menu du moment</h2><p className="mt-3 text-slate-500">Choisissez vos favoris, on s'occupe du reste.</p></div><div className="relative"><Search size={17} className="absolute left-4 top-3.5 text-slate-400"/><input placeholder="Rechercher un plat" className="w-full rounded-full border border-emerald/15 bg-[#f7fbf9] py-3 pl-11 pr-4 text-sm outline-none focus:border-emerald md:w-56"/></div></div><div className="my-8 flex gap-2 overflow-x-auto pb-2">{cats.map(c => <button key={c} onClick={() => setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold transition ${category === c ? 'bg-emerald text-white' : 'bg-mint text-emerald hover:bg-lime'}`}>{c}</button>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item => <FoodCard key={item.id} item={item} add={add}/>)}</div></div></section>
      <section id="about" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2 lg:px-10"><div className="rounded-[2.5rem] bg-mint p-8 sm:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald">Pourquoi Tasty</p><h2 className="mt-4 text-4xl font-black tracking-tight">Bien manger devrait être simple.</h2><p className="mt-5 leading-7 text-slate-600">Nous travaillons avec des producteurs locaux et une équipe passionnée pour créer une cuisine saine, joyeuse et accessible.</p><div className="mt-8 grid gap-5 sm:grid-cols-3">{[['01','Produits frais'],['02','Fait maison'],['03','Zéro gâchis']].map(x => <div key={x[0]}><b className="text-2xl text-emerald">{x[0]}</b><p className="mt-1 text-sm font-semibold">{x[1]}</p></div>)}</div></div><Reservation message={message}/></section>
      </main>
    </>}
    <footer className="border-t border-emerald/10 bg-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 py-8 text-sm text-slate-500 md:flex-row lg:px-10"><span className="font-bold text-ink">Tasty<span className="text-emerald">.</span></span><span>© 2025 Tasty Kitchen · Paris & livraison</span><span className="flex gap-4"><a href="#menu" className="hover:text-emerald">Menu</a><a href="#reserve" className="hover:text-emerald">Contact</a></span></div></footer>
  </div>;
}
function Reservation({ message }) { const [done,setDone]=useState(false); return <div id="reserve" className="rounded-[2.5rem] bg-ink p-8 text-white sm:p-12"><div className="mb-7 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald"><CalendarDays/></span><div><p className="text-sm font-bold text-lime">À table !</p><h2 className="text-2xl font-black">Réserver une table</h2></div></div>{done ? <div className="rounded-2xl bg-white/10 p-6"><Check className="mb-3 text-lime"/><p className="font-bold">Votre table est réservée !</p><p className="mt-1 text-sm text-white/60">Un email de confirmation vient de partir.</p></div> : <form onSubmit={e => {e.preventDefault();setDone(true);message('Réservation confirmée')}} className="grid gap-4"><input required placeholder="Votre prénom" className="rounded-xl border-0 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-white/45 focus:ring-2 focus:ring-lime"/><div className="grid gap-4 sm:grid-cols-2"><input required type="date" className="rounded-xl border-0 bg-white/10 px-4 py-3 text-sm text-white outline-none [color-scheme:dark] focus:ring-2 focus:ring-lime"/><select className="rounded-xl border-0 bg-white/10 px-4 py-3 text-sm text-white outline-none focus:ring-2 focus:ring-lime"><option className="text-ink">19:30</option><option className="text-ink">20:00</option><option className="text-ink">20:30</option></select></div><div className="grid gap-4 sm:grid-cols-2"><select className="rounded-xl border-0 bg-white/10 px-4 py-3 text-sm text-white outline-none"><option className="text-ink">2 personnes</option><option className="text-ink">4 personnes</option><option className="text-ink">6 personnes</option></select><Button type="submit" className="bg-lime !text-ink hover:bg-white">Réserver <ArrowRight size={16}/></Button></div></form>}</div> }
function Cart({ cart,total,change,setView,message }) { return <main className="mx-auto min-h-[70vh] max-w-4xl px-5 py-16 lg:px-10"><button onClick={()=>setView('order')} className="mb-8 flex items-center gap-2 text-sm font-bold text-emerald"><ChevronRight className="rotate-180" size={16}/> Retour au menu</button><h1 className="text-4xl font-black">Votre commande</h1>{cart.length === 0 ? <div className="mt-10 rounded-3xl bg-white p-12 text-center shadow-soft"><ShoppingBag className="mx-auto text-emerald" size={40}/><p className="mt-4 font-bold">Votre panier est vide</p></div> : <div className="mt-8 grid gap-6 md:grid-cols-[1fr_330px]"> <div className="space-y-3">{cart.map(x=><div key={x.id} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><img src={x.image} className="h-16 w-16 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="font-bold">{x.name}</p><p className="text-sm text-emerald">€{x.price.toFixed(2)}</p></div><div className="flex items-center gap-3 rounded-full bg-mint px-2 py-1"><button onClick={()=>change(x.id,-1)}><Minus size={15}/></button><span className="text-sm font-bold">{x.qty}</span><button onClick={()=>change(x.id,1)}><Plus size={15}/></button></div></div>)}</div><div className="h-fit rounded-3xl bg-ink p-6 text-white"><p className="font-bold">Résumé</p><div className="my-5 flex justify-between border-b border-white/10 pb-5 text-sm text-white/60"><span>Sous-total</span><span>€{total.toFixed(2)}</span></div><div className="flex justify-between text-lg font-black"><span>Total</span><span>€{total.toFixed(2)}</span></div><Button onClick={()=>message('Commande envoyée en cuisine !')} className="mt-6 w-full bg-lime !text-ink hover:bg-white">Payer la commande <CreditCard size={16}/></Button></div></div>}</main> }
function Dashboard({setView,tab,setTab,message}) { const tabs=[['reservations','Réservations',CalendarDays],['pos','Caisse / commandes',CreditCard],['kitchen','Cuisine',ChefHat]]; return <main className="mx-auto min-h-[75vh] max-w-7xl px-5 py-10 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><button onClick={()=>setView('order')} className="mb-5 flex items-center gap-2 text-sm font-bold text-emerald"><ChevronRight className="rotate-180" size={16}/> Vue client</button><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald">Espace équipe</p><h1 className="mt-2 text-4xl font-black">Bonjour, Tasty 👋</h1><p className="mt-2 text-slate-500">Mardi 18 juin · service du soir</p></div><div className="rounded-2xl bg-white px-5 py-4 shadow-sm"><p className="text-xs text-slate-400">Chiffre d'affaires aujourd'hui</p><p className="text-2xl font-black text-emerald">€2 486,40 <span className="text-xs font-medium text-emerald">+12.4%</span></p></div></div><div className="mt-10 flex gap-2 overflow-x-auto border-b border-emerald/10">{tabs.map(([id,label,Icon])=><button onClick={()=>setTab(id)} key={id} className={`flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab===id?'border-emerald text-emerald':'border-transparent text-slate-400'}`}><Icon size={17}/>{label}</button>)}</div><div className="mt-8 fade-in">{tab==='reservations' && <OpsCard icon={CalendarDays} title="Réservations du jour" action="Ajouter une réservation" message={message} rows={[['19:00','Léa Martin','4 personnes','Confirmée'],['19:30','Thomas Bernard','2 personnes','Confirmée'],['20:15','Camille Roy','6 personnes','En attente']]}/>} {tab==='pos' && <OpsCard icon={CreditCard} title="Commandes en cours" action="Nouvelle commande" message={message} rows={[['#1048','Sur place · Table 12','€42,80','À encaisser'],['#1047','À emporter · Léonie','€28,50','Payée'],['#1046','Livraison · Alex D.','€64,20','En préparation']]}/>} {tab==='kitchen' && <OpsCard icon={ChefHat} title="File de préparation" action="Marquer tout prêt" message={message} rows={[['#1048','2 bowls · 1 lemonade','Table 12','En préparation'],['#1046','3 plats · 2 desserts','Livraison','À lancer'],['#1045','1 brunch · 1 café','Table 4','Prêt']]}/>}</div></main> }
function OpsCard({icon:Icon,title,action,message,rows}) {return <div className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="flex flex-col justify-between gap-4 border-b border-emerald/10 p-6 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-mint text-emerald"><Icon size={20}/></span><div><h2 className="font-black">{title}</h2><p className="text-sm text-slate-400">{rows.length} éléments à traiter</p></div></div><Button onClick={()=>message('Action enregistrée')}>{action} <Plus size={16}/></Button></div><div className="divide-y divide-emerald/10">{rows.map((r,i)=><div key={i} className="grid gap-2 p-5 sm:grid-cols-[.7fr_1.5fr_1fr_auto] sm:items-center"><span className="font-bold text-emerald">{r[0]}</span><span className="font-semibold">{r[1]}</span><span className="text-sm text-slate-500">{r[2]}</span><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${r[3]==='Confirmée'||r[3]==='Payée'||r[3]==='Prêt'?'bg-lime text-emerald':'bg-amber-100 text-amber-700'}`}>{r[3]}</span></div>)}</div></div>}

createRoot(document.getElementById('root')).render(<App />);